spring.application.name=demo
#tink.client-secret=${CLIENT_SECRET}
#tink.client-id=${CLIENT_ID}
#tink.redirect-uri=${REDIRECT_URI}
tink.client_secret=d0560f86a79b4f4da9874e91d428ad34
tink.client_id=531734aaaf8d4a5bbb092ccdaa6b769b
tink.redirect_uri=http://localhost:8080/callback